/'
https://plantuml.com/en/class-diagram
http://www.plantuml.com/plantuml/uml/
'/
@startuml
page 2x2

class Car

package foo2 {
class Dummy #LightGreen {
--Требования--
 -field1
 #field2
--Эффект--
 ~method1
 +method2()
}
note left: Пояснение/лор

class Dummy2 << (Ы,red) >> #LightGreen {
--Требования--
 -field1
 #field2
--Эффект--
 ~method1
 +method2()
}
note left: Пояснение/лор
}

Car -> foo2
@enduml