/'
https://plantuml.com/en/class-diagram
http://www.plantuml.com/plantuml/uml/
'/
@startuml

class Car

Driver - Car : drives >
' Car *- Wheel : have 4 >
Car -- Person : < owns

package foo2 {
class Dummy #LightGreen {
--Требования--
 -field1
 #field2
--Эффект--
 ~method1
 +method2()
}
note left: Пояснение/лор
}

Car -> foo2
@enduml